Feature/new stories table
BloomTech-Labs/scribble-stadium-be pull request #55
Opened 2021-08-03 03:47 UTC by nico-herrera

# Description

Fixes #

- What work was done?
Created a StoriesNew table and migrated data from Stories "Title" row into StoriesNew.Title
- Why was this work done?
 It was a necessary step in order to restructure the database schema.
- What feature / user story is it for?
Feature: Redesign Story Squad Schema || User Story: NA Backend Feature
- Any relevant links or images / screenshots
N/A

## Type of change

Please delete options that are not relevant.

- [ x] New feature (non-breaking change which adds functionality)

## Change Status

- [ x] Complete, but not tested (may need new tests)

## Has This Been Tested

- [ ] Yes
- [x ] No
- [ ] Not necessary

## Checklist

- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] My code has been reviewed by at least one peer
- [ x] My changes generate no new warnings
- [x ] There are no merge conflicts

2021-08-03 04:25 UTC, lukecparr requested changes
Looks like you'll need to run the linter and fix these issues. I know there are some instructions in the 'CONTRIBUTING.md' file if needed.

2021-08-04 01:35 UTC, ChadDiaz commented on data/migrations/20210802205311_stories_new.js
> +  return knex.schema.createTable('StoriesNew', (tbl) => {
Look at the table name. I feel the convention overall has been to use a hyphen.

2021-08-04 01:36 UTC, ChadDiaz approved these changes
Code looks clean.  Great job!

2021-08-04 01:38 UTC, lukecparr approved these changes

2021-08-04 01:38 UTC, merged

2021-08-04 01:38 UTC, lukecparr commented
Check pass and everything looks good 👍🏻

2021-08-04 01:39 UTC, nico-herrera reviewed
i have formatted my code