Feature/wordcloud back end
BloomTech-Labs/scribble-stadium-be pull request #83
Opened 2021-10-14 03:33 UTC by casey-dietz

# Description

Fixes #

- What work was done? Created the wordCloudRouter consuming the word cloud gif from the DS API.
- Why was this work done? To link the DS API to the FE so they can present the gif on the client.
- What feature / user story is it for? Make a stakeholder-worthy crop cloud
- Any relevant links or images / screenshots
- https://trello.com/c/szLwC13f
- https://www.loom.com/share/b24faa8fecb5423980de4ae6bb35c882

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Change Status

- [x] Complete, but not tested (may need new tests) Functionality was tested in Postman but no new unit tests have been written. 

## Has This Been Tested

- [x] Yes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

2021-10-14 05:28 UTC, Kyleswillard submitted a review, later dismissed
Overall good code! Glad  we got this figured out! Remember to add a loom vid to the PR.

2021-10-16 19:35 UTC, tonysorensen submitted a review, later dismissed

2021-10-16 19:35 UTC, tonysorensen commented on api/wordCloud/wordCloudRouter.js
> +const { default: axios } = require('axios');
I had to look up what using default here did and as far as I can gather it's just another way to import that improves autocompletion in the IDE? Let me know if it does more than that because I already think it's a nifty trick and I'll have to remember it.

2021-10-16 19:35 UTC, tonysorensen commented on api/wordCloud/wordCloudRouter.js
> + *     - okta: []
Good job figuring out the swagger documentation, but shouldn't our security be Auth0 now?

2021-10-16 19:58 UTC, casey-dietz commented on api/wordCloud/wordCloudRouter.js
> + *     - okta: []
I thought the same thing, but I was referencing all of the other endpoint docs and all of them listed okta for security still, so I rolled with that. I figured if it needs to be updated it will likely all need to be done at same time.

2021-10-16 20:13 UTC, tonysorensen commented on api/wordCloud/wordCloudRouter.js
> + *     - okta: []
I see, I think I changed a couple. This brings up a good point for discussion and maybe Ash or Derek can shed some light on it and possibly address it with future cohorts. We didn't discuss the Swagger documentation at any great length and it may be something they want to comment on one way or another.

2021-10-19 04:26 UTC, Aaron-TheCreator submitted a review, later dismissed
the simplicity of using a GET method to axios.post to the DsApi and returning the .data property on the res object is pretty cool. clean code, atomic commits. awesome

2021-10-19 22:53 UTC, tonysorensen approved these changes
Looks great!

2021-10-20 01:41 UTC, Kyleswillard requested changes

2021-10-20 01:41 UTC, Kyleswillard commented on api/wordCloud/wordCloudRouter.js
> + * /wordcloud:
Please remove dead code.

2021-10-20 01:44 UTC, casey-dietz commented on api/wordCloud/wordCloudRouter.js
> + * /wordcloud:
This is how we have to document in the backend. I have to use the @swagger tag

2021-10-20 01:49 UTC, Kyleswillard commented on api/wordCloud/wordCloudRouter.js
> + * /wordcloud:
Oh Good call. Saw the comment and ignored the swagger decorator. My bad!

2021-10-21 02:47 UTC, Aaron-TheCreator approved these changes
good catch changing "okta" to "Auth0" in the `@swagger` docs!

2021-10-27 02:08 UTC, Kyleswillard approved these changes

2021-10-27 02:13 UTC, merged