Deprecated routes removal
BloomTech-Labs/scribble-stadium-be pull request #88
Opened 2021-11-03 01:48 UTC by Veilios

# Description

Fixes #

- What work was done?
   removed some routes in submissionRouter
- Why was this work done?
    These routes were no longer being used by backend
- What feature / user story is it for?
- Any relevant links or images / screenshots

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [ ] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

## Trello Card
- https://trello.com/c/ZzEyBH77/689-remove-deprecated-routes-in-the-be-ensure-they-are-not-being-used-anywhere-before-removing-them

2021-11-03 19:59 UTC, Ksouffle requested changes
Nice job. You can actually delete the entire submission folder because the routes that replace this are in the child folder. After doing so, please remove the submissions-test.js file and its import in \_\_tests\_\_/index.js. Also, we don't want to push up any changes to the package-lock.json file, so go ahead and run `git checkout origin/main package-lock.json` to restore the main version, then push it up 👍

2021-11-03 19:59 UTC, Ksouffle commented on api/submission/submissionRouter.js
>  });
I'm curious why you left in the /write/:id delete route.

2021-11-04 03:31 UTC, Ksouffle approved these changes
Nice job! Looks good to me

2021-11-04 03:33 UTC, ashtilawat23 approved these changes

2021-11-04 03:33 UTC, merged